blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/narevai/narev/discussions
    about: Ask questions and discuss ideas here
  - name: Documentation
    url: https://github.com/narevai/narev#readme
    about: Check the docs before reporting issues
