services:
  dev:
    build:
      context: ../backend
      dockerfile: ../.devcontainer/Dockerfile.dev
    command: sleep infinity
    env_file:
      - path: "../.env"
        required: false
    ports:
      - "8000:8000"
    volumes:
      - ..:/workspace
      - pip_cache:/root/.cache/pip
      - backend_data:/workspace/backend/data
      - backend_logs:/workspace/backend/logs

volumes:
  pip_cache:
  backend_data:
  backend_logs:
